### ISSUE TITLE
Faulty maze generated for certain sizes

### ISSUE THREAD

**Issue by cupofjoakim** [primaryobjects/maze-generator#1]
Hey, cool project! Just wanted to document that I found some sizes to break the maze generation. Example for 60x30 below:

![maze-generated-60x30](https://user-images.githubusercontent.com/2109753/55950849-263d3880-5c56-11e9-8089-2951c18ff199.png)

**Comment by primaryobjects** [comment]
Please feel free to submit a PR for an update. Thank you!
